"""Internal billing model — plans, invoices, invoice lines.

Platform-level (no RLS): these are Auphere's billing records, never
exposed to a tenant. The payer of an invoice is EITHER a partner (agency,
billed for all its tenants) OR a single direct tenant — enforced by a DB
CHECK, mirrored here by :meth:`Invoice.payer_kind`.

All amounts are USD cents (integers). Stripe integration lands later; the
``stripe_*`` columns are intentionally absent until then.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from nexus_api.db.base import Base
from nexus_api.db.models._mixins import TimestampMixin, UUIDPrimaryKey


class InvoiceStatus(str, enum.Enum):
    DRAFT = "draft"  # generated by the cron, not yet sent
    ISSUED = "issued"  # sent to the payer, awaiting payment
    PAID = "paid"
    VOID = "void"  # cancelled; never counts toward revenue


class BillingPlan(UUIDPrimaryKey, TimestampMixin, Base):
    """A named monthly price. ``tenants.billing_plan_id`` points here for
    the base rate; a tenant's ``price_override_cents`` wins when set."""

    __tablename__ = "billing_plans"
    __table_args__ = (
        CheckConstraint("monthly_amount_cents >= 0", name="ck_billing_plans_amount_nonneg"),
    )

    code: Mapped[str] = mapped_column(String(40), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    monthly_amount_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))


class Invoice(UUIDPrimaryKey, TimestampMixin, Base):
    """One month's charges for one payer (a partner OR a direct tenant)."""

    __tablename__ = "invoices"
    __table_args__ = (
        CheckConstraint(
            "(partner_id IS NOT NULL) <> (tenant_id IS NOT NULL)",
            name="ck_invoices_one_payer",
        ),
        CheckConstraint("period_month BETWEEN 1 AND 12", name="ck_invoices_period_month"),
        CheckConstraint("status IN ('draft', 'issued', 'paid', 'void')", name="ck_invoices_status"),
    )

    partner_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("partners.id", ondelete="RESTRICT"), nullable=True
    )
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="RESTRICT"), nullable=True
    )
    period_year: Mapped[int] = mapped_column(Integer, nullable=False)
    period_month: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=InvoiceStatus.DRAFT.value
    )
    total_cents: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="USD")
    issued_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    @property
    def payer_kind(self) -> str:
        """``"partner"`` or ``"direct"`` — which side of the CHECK is set."""
        return "partner" if self.partner_id is not None else "direct"


class InvoiceLine(UUIDPrimaryKey, Base):
    """One tenant's charge within an invoice. A partner invoice has many;
    a direct invoice has exactly one (the tenant itself)."""

    __tablename__ = "invoice_lines"

    invoice_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("invoices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="RESTRICT"), nullable=False
    )
    description: Mapped[str] = mapped_column(String(255), nullable=False)
    amount_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
