/**
 * Catálogo de oportunidades (24, 8 categorías × 3). Determinista: el orden de
 * este array desempata en el ranking. Sin cifras de ahorro ni garantías.
 *
 * TODO_COMERCIAL: validar con Amacrux los campos `amacruxFit` y
 * `commercialCta`, y qué herramientas de `relatedTools` quieren nombrar.
 */
import type { ProfileSegment } from "./enums";
import type { Opportunity } from "./types";

const ALL_PROFILES: ProfileSegment[] = [];

export const OPPORTUNITIES: Opportunity[] = [
  // ── Automatización operativa ────────────────────────────────────────────
  {
    id: "clasificacion-solicitudes",
    title: "Clasificar y enrutar solicitudes automáticamente",
    category: "automatizacion_operativa",
    applicableProfiles: ["decisor_negocio", "operaciones", "marketing_ventas", "consultor_independiente"],
    applicableSectors: [],
    problemSignals: ["emails_solicitudes", "tareas_manuales", "atencion_cliente"],
    desiredOutcomes: ["ahorrar_tiempo", "mejorar_atencion", "reducir_errores"],
    maturityRange: ["explorador", "escalador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–3 semanas",
    problemSolved: "Las solicitudes llegan mezcladas por correo, WhatsApp o formularios y alguien tiene que leerlas, clasificarlas y pasarlas a la persona adecuada.",
    howItWorks: "Un flujo lee cada solicitud entrante, la clasifica por tipo y urgencia con IA, extrae los datos clave y la asigna o responde con una plantilla cuando procede.",
    benefitDescription: "Puede reducir el tiempo de triaje y mejorar los tiempos de respuesta; el equipo se concentra en los casos que requieren criterio.",
    requiredInputs: ["Ejemplos reales de solicitudes de los últimos meses", "Tipos de solicitud y quién atiende cada uno", "Canal por el que llegan (correo, WhatsApp, formulario)"],
    recommendedFirstStep: "Elegir un solo canal y un solo tipo de solicitud, y medir cuántas llegan a la semana.",
    amacruxFit: "Amacrux puede montar el flujo de clasificación y conectarlo con el correo o el WhatsApp que ya usan.",
    relatedTools: ["Correo corporativo", "WhatsApp Business", "Formularios web", "Hoja de cálculo o CRM"],
    commercialCta: "Analizar el canal de solicitudes con Amacrux",
  },
  {
    id: "recordatorios-y-seguimiento",
    title: "Recordatorios y seguimientos automáticos",
    category: "automatizacion_operativa",
    applicableProfiles: ["decisor_negocio", "operaciones", "marketing_ventas", "consultor_independiente"],
    applicableSectors: ["comercio_retail", "salud_farmacia", "hosteleria_turismo", "servicios_profesionales", "educacion"],
    problemSignals: ["tareas_manuales", "planificacion_equipos", "ventas_leads"],
    desiredOutcomes: ["ahorrar_tiempo", "reducir_errores", "mejorar_atencion"],
    maturityRange: ["explorador", "integrador"],
    technicalComplexity: 1,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "1–2 semanas",
    problemSolved: "Citas, vencimientos, pagos pendientes o tareas de seguimiento dependen de que alguien se acuerde de avisar.",
    howItWorks: "Reglas sencillas sobre los datos que ya existen (agenda, cobros, pedidos) disparan mensajes por WhatsApp o correo en el momento adecuado, con registro de lo enviado.",
    benefitDescription: "Menos olvidos y menos tiempo persiguiendo; el seguimiento deja de depender de la memoria de una persona.",
    requiredInputs: ["Dónde están hoy las fechas y los estados (agenda, hoja de cálculo, sistema)", "Plantillas de mensaje aprobadas", "Horarios y límites de envío"],
    recommendedFirstStep: "Listar los tres recordatorios que más se olvidan y cuántos se envían a mano cada semana.",
    amacruxFit: "Amacrux integra los recordatorios con la agenda o el sistema de cobros que ya usan; encaja con herramientas de cobro como Amigable Cobro.",
    relatedTools: ["WhatsApp Business", "Agenda o calendario", "Sistema de cobros", "Hojas de cálculo"],
    commercialCta: "Definir un piloto de recordatorios",
  },
  {
    id: "flujos-aprobacion",
    title: "Flujos de aprobación y tareas sin correos cruzados",
    category: "automatizacion_operativa",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico"],
    applicableSectors: [],
    problemSignals: ["tareas_manuales", "planificacion_equipos", "operaciones_logistica", "sin_tiempo_innovar"],
    desiredOutcomes: ["productividad", "reducir_errores", "escalar"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "Aprobaciones, pedidos internos o cambios de turno se gestionan por correo y chat, sin saber en qué estado están.",
    howItWorks: "Un flujo guiado recoge la petición, la envía a quien debe aprobar, avisa si se retrasa y deja un registro consultable por todos.",
    benefitDescription: "Impacto operativo relevante en equipos con muchas peticiones internas: menos esperas y trazabilidad de cada decisión.",
    requiredInputs: ["Los dos o tres procesos con más idas y vueltas", "Quién aprueba qué y en cuánto tiempo", "Herramienta donde el equipo ya trabaja"],
    recommendedFirstStep: "Dibujar en una hoja el proceso de aprobación más frecuente, con sus pasos y sus esperas.",
    amacruxFit: "Amacrux diseña el flujo y lo construye sobre herramientas ligeras o sobre el software de gestión existente.",
    relatedTools: ["Software de gestión", "Herramientas de flujo de trabajo", "Correo y chat del equipo"],
    commercialCta: "Revisar el proceso de aprobaciones con Amacrux",
  },

  // ── IA para conocimiento y soporte ───────────────────────────────────────
  {
    id: "asistente-interno-conocimiento",
    title: "Asistente interno que responde con la documentación de la empresa",
    category: "ia_conocimiento_soporte",
    applicableProfiles: ["decisor_negocio", "operaciones", "tecnologico", "ingenieria", "consultor_independiente"],
    applicableSectors: [],
    problemSignals: ["busqueda_interna", "soporte_interno", "emails_solicitudes", "documentacion_tecnica"],
    desiredOutcomes: ["ahorrar_tiempo", "productividad", "reducir_errores"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–4 semanas",
    problemSolved: "Las mismas preguntas se repiten y la respuesta está en documentos, manuales o en la cabeza de dos personas.",
    howItWorks: "Un asistente con IA consulta solo la documentación autorizada (procedimientos, políticas, catálogos) y responde citando la fuente; lo que no está documentado lo deriva a una persona.",
    benefitDescription: "Puede reducir interrupciones y acelerar la incorporación de personas nuevas; la calidad depende de la documentación disponible.",
    requiredInputs: ["Documentación existente y quién la mantiene", "Preguntas más frecuentes del equipo", "Qué información es confidencial"],
    recommendedFirstStep: "Reunir los diez documentos que más se consultan y las veinte preguntas más repetidas.",
    amacruxFit: "Amacrux monta el asistente sobre la documentación existente y define qué puede y qué no puede responder.",
    relatedTools: ["Documentos y wikis internos", "Chat del equipo", "Sistemas de gestión"],
    warning: "Requiere documentación mínimamente ordenada; si no existe, el primer paso es crearla.",
    commercialCta: "Explorar un asistente interno con Amacrux",
  },
  {
    id: "triaje-atencion-cliente",
    title: "Triaje inteligente de atención al cliente",
    category: "ia_conocimiento_soporte",
    applicableProfiles: ["decisor_negocio", "operaciones", "marketing_ventas"],
    applicableSectors: ["comercio_retail", "hosteleria_turismo", "salud_farmacia", "finanzas_seguros", "tecnologia_software"],
    problemSignals: ["atencion_cliente", "emails_solicitudes", "soporte_interno"],
    desiredOutcomes: ["mejorar_atencion", "escalar", "ahorrar_tiempo"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "El equipo de atención responde a mano a consultas repetitivas mientras las urgentes esperan en la misma cola.",
    howItWorks: "La IA clasifica cada conversación por intención y urgencia, propone una respuesta para las frecuentes y escala a una persona las que requieren criterio, siempre con revisión humana al principio.",
    benefitDescription: "Puede mejorar los tiempos de respuesta y liberar al equipo para los casos complejos; requiere validar volumen y tipos de consulta.",
    requiredInputs: ["Histórico de conversaciones o correos de atención", "Respuestas aprobadas para las consultas frecuentes", "Criterios de escalado"],
    recommendedFirstStep: "Clasificar a mano cien conversaciones recientes para ver qué porcentaje es repetitivo y qué no.",
    amacruxFit: "Amacrux construye el triaje sobre el canal actual (WhatsApp, correo o web) con supervisión humana desde el primer día.",
    relatedTools: ["WhatsApp Business", "Correo de atención", "Chat web", "CRM o sistema de tickets"],
    commercialCta: "Analizar la atención al cliente con Amacrux",
  },
  {
    id: "respuestas-guiadas-whatsapp",
    title: "Respuestas guiadas en WhatsApp para consultas frecuentes",
    category: "ia_conocimiento_soporte",
    applicableProfiles: ["decisor_negocio", "marketing_ventas", "consultor_independiente", "operaciones"],
    applicableSectors: ["comercio_retail", "hosteleria_turismo", "salud_farmacia", "servicios_profesionales", "educacion"],
    problemSignals: ["atencion_cliente", "emails_solicitudes", "ventas_leads"],
    desiredOutcomes: ["mejorar_atencion", "ahorrar_tiempo", "aumentar_ventas"],
    maturityRange: ["explorador", "integrador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–3 semanas",
    problemSolved: "Horarios, precios, disponibilidad y estado de pedidos se contestan uno a uno por WhatsApp, a cualquier hora.",
    howItWorks: "Un asistente responde en WhatsApp a las consultas frecuentes con información aprobada y actualizada, y pasa la conversación a una persona cuando hace falta.",
    benefitDescription: "Respuesta inmediata fuera de horario y menos interrupciones; el negocio decide qué responde el asistente y qué no.",
    requiredInputs: ["Lista de consultas frecuentes con su respuesta", "Fuente de datos para disponibilidad o precios", "Horario de atención humana"],
    recommendedFirstStep: "Anotar durante una semana las consultas que llegan por WhatsApp y agruparlas.",
    amacruxFit: "Amacrux despliega el asistente en el número de WhatsApp del negocio y lo conecta con el catálogo o la agenda; encaja con Amigable Venta para catálogo y stock.",
    relatedTools: ["WhatsApp Business", "Catálogo o punto de venta", "Agenda"],
    commercialCta: "Probar un asistente de WhatsApp con Amacrux",
  },

  // ── Automatización comercial ──────────────────────────────────────────────
  {
    id: "cualificacion-leads",
    title: "Cualificación y seguimiento de clientes potenciales",
    category: "automatizacion_comercial",
    applicableProfiles: ["marketing_ventas", "decisor_negocio", "consultor_independiente"],
    applicableSectors: [],
    problemSignals: ["ventas_leads", "emails_solicitudes", "tareas_manuales"],
    desiredOutcomes: ["aumentar_ventas", "ahorrar_tiempo", "escalar"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–4 semanas",
    problemSolved: "Los contactos llegan por varios canales, se responden tarde y no se sabe cuáles merecen una llamada.",
    howItWorks: "Cada contacto nuevo se registra, se cualifica con unas preguntas o con IA según lo que escribió, se prioriza y recibe un primer seguimiento automático; el equipo ve una lista ordenada.",
    benefitDescription: "Alto potencial en equipos comerciales pequeños: menos contactos perdidos y mejor uso del tiempo de venta.",
    requiredInputs: ["Canales por los que llegan los contactos", "Criterios de cualificación actuales", "Dónde se registran hoy (CRM, hoja, nada)"],
    recommendedFirstStep: "Contar cuántos contactos llegaron el último mes y cuántos recibieron respuesta en menos de un día.",
    amacruxFit: "Amacrux conecta los canales de entrada con un CRM sencillo y automatiza la cualificación y el primer seguimiento.",
    relatedTools: ["CRM", "Formularios web", "WhatsApp Business", "Correo"],
    commercialCta: "Revisar el proceso comercial con Amacrux",
  },
  {
    id: "generacion-presupuestos",
    title: "Presupuestos y propuestas asistidos por IA",
    category: "automatizacion_comercial",
    applicableProfiles: ["marketing_ventas", "decisor_negocio", "consultor_independiente", "operaciones"],
    applicableSectors: ["servicios_profesionales", "industria_logistica", "tecnologia_software", "comercio_retail"],
    problemSignals: ["presupuestos", "ventas_leads", "documental"],
    desiredOutcomes: ["aumentar_ventas", "ahorrar_tiempo", "reducir_errores"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "Cada presupuesto se redacta desde cero o copiando el anterior, con errores de precios y tiempos de entrega largos.",
    howItWorks: "A partir de una plantilla aprobada y de la lista de precios, la IA prepara un borrador con los datos del cliente y las opciones elegidas; una persona revisa y envía.",
    benefitDescription: "Puede acortar el tiempo de respuesta comercial y reducir errores de precio; el criterio comercial sigue siendo humano.",
    requiredInputs: ["Plantillas de propuesta actuales", "Lista de precios y condiciones", "Ejemplos de propuestas ganadas"],
    recommendedFirstStep: "Elegir el tipo de presupuesto más frecuente y medir cuánto se tarda hoy en enviarlo.",
    amacruxFit: "Amacrux construye el generador sobre las plantillas y precios de la empresa, con revisión antes del envío.",
    relatedTools: ["Plantillas de documentos", "Lista de precios", "CRM", "Correo"],
    commercialCta: "Explorar presupuestos asistidos con Amacrux",
  },
  {
    id: "seguimiento-oportunidades",
    title: "Seguimiento automático de oportunidades abiertas",
    category: "automatizacion_comercial",
    applicableProfiles: ["marketing_ventas", "decisor_negocio"],
    applicableSectors: [],
    problemSignals: ["ventas_leads", "planificacion_equipos", "visibilidad_datos"],
    desiredOutcomes: ["aumentar_ventas", "decisiones", "escalar"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "proyecto_integracion",
    expectedTimeToPilot: "4–6 semanas",
    problemSolved: "Las oportunidades se enfrían porque nadie recuerda hacer el siguiente contacto ni se ve el estado del embudo.",
    howItWorks: "El CRM avisa de oportunidades sin actividad, propone el siguiente paso y prepara el mensaje; un panel muestra el embudo actualizado.",
    benefitDescription: "Más oportunidades atendidas a tiempo y visibilidad del embudo para decidir dónde poner el esfuerzo.",
    requiredInputs: ["CRM o registro de oportunidades", "Etapas del proceso de venta", "Reglas de seguimiento acordadas"],
    recommendedFirstStep: "Definir las etapas del embudo y el tiempo máximo sin actividad en cada una.",
    amacruxFit: "Amacrux configura el CRM y automatiza los avisos y mensajes de seguimiento.",
    relatedTools: ["CRM", "Correo", "WhatsApp Business", "Panel de datos"],
    warning: "Necesita un CRM o registro de oportunidades mantenido; si no existe, empieza por «Cualificación y seguimiento de clientes potenciales».",
    commercialCta: "Ordenar el embudo comercial con Amacrux",
  },

  // ── Procesamiento documental ──────────────────────────────────────────────
  {
    id: "extraccion-pdf-facturas",
    title: "Extraer datos de facturas, PDF y correos sin teclearlos",
    category: "procesamiento_documental",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico"],
    applicableSectors: [],
    problemSignals: ["extraccion_datos", "documental", "copiar_datos"],
    desiredOutcomes: ["ahorrar_tiempo", "reducir_errores", "reducir_costes"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "Facturas, albaranes o formularios llegan en PDF o foto y alguien copia los datos a mano al sistema.",
    howItWorks: "La IA lee cada documento, extrae los campos acordados, los valida contra reglas (totales, fechas, proveedores) y los deja listos para revisar e importar.",
    benefitDescription: "Puede reducir tareas manuales y errores de transcripción; los casos dudosos siguen pasando por una persona.",
    requiredInputs: ["Muestra de documentos reales (variedad de proveedores y formatos)", "Campos que hay que extraer", "Sistema de destino"],
    recommendedFirstStep: "Reunir cincuenta documentos recientes y anotar cuánto tiempo se dedica a teclearlos cada semana.",
    amacruxFit: "Amacrux monta la extracción y la integra con el sistema contable o de gestión que ya usan.",
    relatedTools: ["Correo", "Sistema contable o de gestión", "Carpetas compartidas"],
    commercialCta: "Analizar la extracción de documentos con Amacrux",
  },
  {
    id: "clasificacion-documental",
    title: "Clasificar y archivar documentos automáticamente",
    category: "procesamiento_documental",
    applicableProfiles: ["operaciones", "decisor_negocio", "consultor_independiente"],
    applicableSectors: ["servicios_profesionales", "finanzas_seguros", "sector_publico", "salud_farmacia", "educacion"],
    problemSignals: ["documental", "busqueda_interna", "tareas_manuales"],
    desiredOutcomes: ["ahorrar_tiempo", "reducir_errores", "productividad"],
    maturityRange: ["explorador", "integrador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–4 semanas",
    problemSolved: "Contratos, expedientes y justificantes se guardan en carpetas distintas con nombres distintos y cuesta encontrarlos.",
    howItWorks: "Cada documento nuevo se clasifica por tipo, cliente y fecha, se renombra según una convención y se archiva en su sitio con metadatos para buscarlo.",
    benefitDescription: "Menos tiempo buscando y menos documentos perdidos; base para cualquier automatización posterior.",
    requiredInputs: ["Tipos de documento y estructura de carpetas deseada", "Dónde llegan los documentos hoy", "Quién debe poder verlos"],
    recommendedFirstStep: "Acordar la convención de nombres y carpetas para los cinco tipos de documento más frecuentes.",
    amacruxFit: "Amacrux configura la clasificación sobre el almacenamiento que ya usan (Drive, OneDrive o servidor).",
    relatedTools: ["Google Drive u OneDrive", "Correo", "Gestor documental"],
    commercialCta: "Ordenar el archivo documental con Amacrux",
  },
  {
    id: "validacion-formularios",
    title: "Validar y completar formularios y expedientes con IA",
    category: "procesamiento_documental",
    applicableProfiles: ["operaciones", "tecnologico", "decisor_negocio"],
    applicableSectors: ["finanzas_seguros", "sector_publico", "salud_farmacia", "servicios_profesionales"],
    problemSignals: ["extraccion_datos", "documental"],
    desiredOutcomes: ["reducir_errores", "ahorrar_tiempo", "escalar"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 4,
    complexityLabel: "proyecto_integracion",
    expectedTimeToPilot: "5–8 semanas",
    problemSolved: "Los expedientes llegan incompletos o con datos inconsistentes y se detecta tarde, con idas y vueltas con el cliente.",
    howItWorks: "Al recibir un expediente, la IA comprueba que estén todos los documentos, cruza datos entre ellos y pide al cliente lo que falta antes de que una persona lo revise.",
    benefitDescription: "Impacto relevante en procesos con muchos expedientes: menos rechazos tardíos y revisión humana centrada en lo importante.",
    requiredInputs: ["Lista de comprobación del expediente", "Ejemplos de expedientes completos e incompletos", "Sistema donde se tramitan"],
    recommendedFirstStep: "Medir cuántos expedientes llegan incompletos y cuál es el motivo más frecuente.",
    amacruxFit: "Amacrux construye la validación e integra la comunicación con el cliente para completar lo que falta.",
    relatedTools: ["Gestor de expedientes", "Correo", "Formularios web", "Firma electrónica"],
    warning: "Requiere reglas de validación claras y un sistema donde se tramiten los expedientes.",
    commercialCta: "Analizar la validación de expedientes con Amacrux",
  },

  // ── Datos y reporting ─────────────────────────────────────────────────────
  {
    id: "reporting-automatico",
    title: "Informes periódicos que se generan solos",
    category: "datos_reporting",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico", "marketing_ventas"],
    applicableSectors: [],
    problemSignals: ["reporting", "visibilidad_datos", "copiar_datos"],
    desiredOutcomes: ["datos", "decisiones", "ahorrar_tiempo"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–4 semanas",
    problemSolved: "Cada semana alguien junta datos de varias fuentes en una hoja para preparar el mismo informe.",
    howItWorks: "Los datos se recogen automáticamente de las fuentes acordadas, se consolidan y el informe se envía por correo o chat en la fecha fijada, con un resumen en lenguaje claro generado por IA.",
    benefitDescription: "Puede eliminar horas de preparación manual y evitar errores de copia; el informe llega siempre a tiempo.",
    requiredInputs: ["Fuentes de datos actuales y acceso a ellas", "Formato del informe y destinatarios", "Definición de cada indicador"],
    recommendedFirstStep: "Elegir el informe que más tiempo consume y listar sus fuentes de datos.",
    amacruxFit: "Amacrux conecta las fuentes y automatiza la generación y el envío del informe.",
    relatedTools: ["Hojas de cálculo", "Sistema de gestión o punto de venta", "Herramienta de paneles", "Correo o chat"],
    commercialCta: "Automatizar el reporting con Amacrux",
  },
  {
    id: "panel-operativo",
    title: "Panel operativo con los indicadores clave al día",
    category: "datos_reporting",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico"],
    applicableSectors: [],
    problemSignals: ["visibilidad_datos", "reporting", "operaciones_logistica"],
    desiredOutcomes: ["decisiones", "datos", "escalar"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "proyecto_integracion",
    expectedTimeToPilot: "4–6 semanas",
    problemSolved: "Las decisiones se toman con datos de hace semanas o con intuición porque la información está repartida.",
    howItWorks: "Un panel único se alimenta de los sistemas existentes y muestra los indicadores acordados, con alertas cuando algo se sale de rango.",
    benefitDescription: "Decisiones con datos actualizados y un mismo lenguaje de indicadores para todo el equipo.",
    requiredInputs: ["Los cinco a diez indicadores que de verdad se usan", "Sistemas que contienen esos datos", "Frecuencia de actualización necesaria"],
    recommendedFirstStep: "Acordar en una reunión corta qué cinco indicadores debe ver dirección cada lunes.",
    amacruxFit: "Amacrux modela los datos, construye el panel y deja las conexiones mantenibles.",
    relatedTools: ["Sistema de gestión", "Punto de venta", "Herramienta de paneles", "Base de datos"],
    commercialCta: "Diseñar el panel operativo con Amacrux",
  },
  {
    id: "alertas-por-datos",
    title: "Alertas automáticas cuando los datos avisan",
    category: "datos_reporting",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico", "ingenieria"],
    applicableSectors: ["comercio_retail", "industria_logistica", "salud_farmacia", "finanzas_seguros", "tecnologia_software"],
    problemSignals: ["visibilidad_datos", "operaciones_logistica", "reporting"],
    desiredOutcomes: ["reducir_errores", "decisiones", "reducir_costes"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–4 semanas",
    problemSolved: "Roturas de stock, retrasos o desviaciones se descubren cuando ya han causado un problema.",
    howItWorks: "Reglas sobre los datos existentes (stock, pedidos, cobros, tiempos) envían un aviso a la persona adecuada en cuanto se cruza un umbral, con el contexto necesario para actuar.",
    benefitDescription: "Reacción temprana ante desviaciones; especialmente útil en inventario, cobros y logística.",
    requiredInputs: ["Umbrales que hoy se vigilan a ojo", "Sistema donde viven los datos", "Quién debe recibir cada alerta"],
    recommendedFirstStep: "Listar los tres avisos que hoy llegan tarde y cuánto cuesta cada retraso.",
    amacruxFit: "Amacrux conecta las alertas con el sistema de gestión o inventario; encaja con Amigable Venta para stock y ventas.",
    relatedTools: ["Sistema de inventario o punto de venta", "WhatsApp o correo", "Hojas de cálculo"],
    commercialCta: "Definir alertas con Amacrux",
  },

  // ── IA para desarrollo de software ────────────────────────────────────────
  {
    id: "asistentes-desarrollo",
    title: "Asistentes de IA integrados en el flujo de desarrollo",
    category: "ia_desarrollo",
    applicableProfiles: ["ingenieria", "tecnologico", "producto_innovacion"],
    applicableSectors: [],
    problemSignals: ["desarrollo_software", "sin_tiempo_innovar", "testing_qa"],
    desiredOutcomes: ["acelerar_desarrollo", "productividad", "calidad_producto"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "2–4 semanas",
    problemSolved: "El equipo dedica mucho tiempo a tareas mecánicas de código, revisiones y contexto disperso entre repositorios.",
    howItWorks: "Se integran asistentes de IA en el editor, en las revisiones de código y en la incidencia, con reglas del equipo, contexto del repositorio y guardas de seguridad.",
    benefitDescription: "Puede mejorar la productividad y la consistencia del código; el impacto depende de adoptar prácticas comunes, no solo herramientas.",
    requiredInputs: ["Repositorios y flujo de trabajo actual", "Normas de código y revisión", "Restricciones de seguridad y datos"],
    recommendedFirstStep: "Elegir un equipo y un repositorio para un piloto de cuatro semanas con métricas acordadas.",
    amacruxFit: "Amacrux ayuda a configurar los asistentes con el contexto del equipo y a medir su efecto.",
    relatedTools: ["GitHub o GitLab", "Editor de código", "Herramientas de CI", "Gestor de incidencias"],
    commercialCta: "Explorar IA en el desarrollo con Amacrux",
  },
  {
    id: "generacion-tests-y-qa",
    title: "Generación de pruebas y control de calidad asistido",
    category: "ia_desarrollo",
    applicableProfiles: ["ingenieria", "tecnologico"],
    applicableSectors: [],
    problemSignals: ["testing_qa", "desarrollo_software"],
    desiredOutcomes: ["calidad_producto", "acelerar_desarrollo", "reducir_errores"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "La cobertura de pruebas es baja y las regresiones se detectan en producción.",
    howItWorks: "La IA propone casos de prueba a partir del código y de las incidencias históricas, genera pruebas unitarias y de extremo a extremo, y las integra en la cadena de integración continua.",
    benefitDescription: "Mejor cobertura con menos esfuerzo manual; las pruebas generadas se revisan antes de aceptarse.",
    requiredInputs: ["Repositorios y cadena de integración continua", "Histórico de incidencias", "Áreas críticas del producto"],
    recommendedFirstStep: "Identificar los tres módulos con más incidencias y su cobertura actual.",
    amacruxFit: "Amacrux integra la generación de pruebas en la cadena existente y define los criterios de aceptación.",
    relatedTools: ["Framework de pruebas", "CI/CD", "Gestor de incidencias"],
    commercialCta: "Reforzar el testing con Amacrux",
  },
  {
    id: "documentacion-tecnica-viva",
    title: "Documentación técnica que se mantiene sola",
    category: "ia_desarrollo",
    applicableProfiles: ["ingenieria", "tecnologico", "producto_innovacion"],
    applicableSectors: [],
    problemSignals: ["documentacion_tecnica", "busqueda_interna", "desarrollo_software"],
    desiredOutcomes: ["productividad", "acelerar_desarrollo", "calidad_producto"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–3 semanas",
    problemSolved: "La documentación está desactualizada y las personas nuevas dependen de preguntar.",
    howItWorks: "La IA genera y actualiza documentación a partir del código, las decisiones y los cambios recientes, y un asistente responde preguntas técnicas citando la fuente.",
    benefitDescription: "Incorporación más rápida y menos conocimiento atrapado en personas concretas.",
    requiredInputs: ["Repositorios y decisiones de arquitectura", "Dónde vive la documentación hoy", "Qué preguntas hacen las personas nuevas"],
    recommendedFirstStep: "Elegir un servicio o módulo y generar su documentación como prueba.",
    amacruxFit: "Amacrux monta el flujo de documentación y el asistente técnico sobre los repositorios existentes.",
    relatedTools: ["GitHub o GitLab", "Wiki o portal de documentación", "Chat del equipo"],
    commercialCta: "Poner al día la documentación con Amacrux",
  },

  // ── Integraciones y orquestación ──────────────────────────────────────────
  {
    id: "sincronizacion-entre-herramientas",
    title: "Sincronizar datos entre herramientas sin copiarlos a mano",
    category: "integraciones_orquestacion",
    applicableProfiles: ["operaciones", "decisor_negocio", "tecnologico", "marketing_ventas", "consultor_independiente"],
    applicableSectors: [],
    problemSignals: ["copiar_datos", "tareas_manuales", "visibilidad_datos"],
    desiredOutcomes: ["ahorrar_tiempo", "reducir_errores", "productividad"],
    maturityRange: ["inicial", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "proyecto_integracion",
    expectedTimeToPilot: "3–5 semanas",
    problemSolved: "Los mismos datos (clientes, pedidos, pagos) se teclean en dos o tres herramientas distintas y nunca coinciden.",
    howItWorks: "Una integración mantiene sincronizados los datos entre las herramientas acordadas, con reglas de quién manda en cada campo y un registro de cambios.",
    benefitDescription: "Puede eliminar tareas manuales y discrepancias entre sistemas; es la base para automatizar procesos completos.",
    requiredInputs: ["Herramientas implicadas y si tienen API o exportación", "Qué datos se copian hoy y con qué frecuencia", "Reglas de conflicto"],
    recommendedFirstStep: "Listar los datos que se copian a mano entre dos herramientas y cuántas veces al día.",
    amacruxFit: "Amacrux construye las integraciones y las deja monitorizadas; encaja con Amigable Cobro y Amigable Venta.",
    relatedTools: ["CRM", "Sistema contable", "Punto de venta", "Hojas de cálculo", "Plataformas de integración"],
    commercialCta: "Conectar las herramientas con Amacrux",
  },
  {
    id: "orquestacion-procesos",
    title: "Orquestar un proceso de punta a punta entre sistemas",
    category: "integraciones_orquestacion",
    applicableProfiles: ["operaciones", "tecnologico", "decisor_negocio"],
    applicableSectors: ["industria_logistica", "comercio_retail", "finanzas_seguros", "salud_farmacia", "tecnologia_software"],
    problemSignals: ["copiar_datos", "operaciones_logistica", "planificacion_equipos", "tareas_manuales"],
    desiredOutcomes: ["escalar", "reducir_errores", "productividad", "reducir_costes"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 4,
    complexityLabel: "transformacion_proceso",
    expectedTimeToPilot: "6–8 semanas",
    problemSolved: "Un pedido, una incidencia o un alta pasan por varios sistemas y personas, y se pierde el hilo entre paso y paso.",
    howItWorks: "Un orquestador coordina cada paso del proceso entre sistemas, asigna tareas a personas cuando hace falta, controla tiempos y muestra el estado global.",
    benefitDescription: "Impacto operativo relevante en procesos de alto volumen: menos esperas, menos errores de traspaso y visibilidad del estado.",
    requiredInputs: ["Mapa del proceso actual con sistemas y personas", "Volumen mensual y tiempos por paso", "Excepciones frecuentes"],
    recommendedFirstStep: "Documentar el proceso completo con un caso real, midiendo dónde se para.",
    amacruxFit: "Amacrux diseña la orquestación y la implementa por fases, empezando por el tramo con más fricción.",
    relatedTools: ["Sistema de gestión", "Plataforma de integración", "Herramientas de flujo de trabajo", "Base de datos"],
    warning: "Es un proyecto por fases; conviene tener las integraciones básicas antes de orquestar el proceso completo.",
    commercialCta: "Diseñar la orquestación con Amacrux",
  },
  {
    id: "conector-erp-crm",
    title: "Conector entre el sistema de gestión y el resto de herramientas",
    category: "integraciones_orquestacion",
    applicableProfiles: ["tecnologico", "operaciones", "ingenieria"],
    applicableSectors: [],
    problemSignals: ["copiar_datos", "reporting", "visibilidad_datos"],
    desiredOutcomes: ["datos", "escalar", "reducir_errores"],
    maturityRange: ["integrador", "escalador"],
    technicalComplexity: 4,
    complexityLabel: "proyecto_integracion",
    expectedTimeToPilot: "5–8 semanas",
    problemSolved: "El sistema de gestión es una isla: el resto de herramientas no ven sus datos y viceversa.",
    howItWorks: "Se construye un conector mantenible (API o intercambio de ficheros) que expone los datos del sistema de gestión al resto de herramientas y recibe cambios de vuelta con control de errores.",
    benefitDescription: "Datos consistentes en toda la empresa y base para reporting, automatizaciones y asistentes.",
    requiredInputs: ["Sistema de gestión y sus capacidades de integración", "Herramientas que necesitan los datos", "Responsable del dato en cada sistema"],
    recommendedFirstStep: "Confirmar con el proveedor del sistema de gestión qué formas de integración ofrece.",
    amacruxFit: "Amacrux desarrolla el conector y lo documenta para que el equipo interno pueda mantenerlo.",
    relatedTools: ["Sistema de gestión", "CRM", "Herramienta de paneles", "Plataforma de integración"],
    warning: "Depende de que el sistema de gestión permita integrarse; si no, hay que valorar alternativas.",
    commercialCta: "Estudiar el conector con Amacrux",
  },

  // ── Optimización de producto digital ──────────────────────────────────────
  {
    id: "funcionalidad-ia-en-producto",
    title: "Una funcionalidad con IA dentro de tu producto",
    category: "producto_digital",
    applicableProfiles: ["producto_innovacion", "ingenieria", "tecnologico", "decisor_negocio"],
    applicableSectors: ["tecnologia_software", "finanzas_seguros", "educacion", "servicios_profesionales"],
    problemSignals: ["desarrollo_software", "atencion_cliente", "busqueda_interna"],
    desiredOutcomes: ["calidad_producto", "nuevos_servicios", "aumentar_ventas"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 4,
    complexityLabel: "solucion_estrategica",
    expectedTimeToPilot: "6–10 semanas",
    problemSolved: "El producto tiene datos y flujos donde la IA podría ayudar a quien lo usa, pero no está claro por dónde empezar ni cómo hacerlo con seguridad.",
    howItWorks: "Se identifica un caso de uso concreto (búsqueda, asistente, resumen, recomendación), se prototipa con usuarios reales y se integra en el producto con medición, límites y control de costos.",
    benefitDescription: "Diferenciación y más valor para el usuario; requiere validar con datos reales y medir el costo por uso.",
    requiredInputs: ["Casos de uso candidatos y datos disponibles", "Usuarios para validar el prototipo", "Restricciones de privacidad y costo"],
    recommendedFirstStep: "Elegir un solo caso de uso y definir cómo se medirá su éxito.",
    amacruxFit: "Amacrux prototipa y desarrolla la funcionalidad junto al equipo de producto.",
    relatedTools: ["Producto propio", "Proveedores de modelos de IA", "Analítica de producto"],
    commercialCta: "Explorar IA en tu producto con Amacrux",
  },
  {
    id: "prototipo-validacion",
    title: "Prototipo rápido para validar una idea con usuarios",
    category: "producto_digital",
    applicableProfiles: ["producto_innovacion", "decisor_negocio", "tecnologico", "consultor_independiente", "marketing_ventas"],
    applicableSectors: [],
    problemSignals: ["sin_tiempo_innovar", "desarrollo_software"],
    desiredOutcomes: ["nuevos_servicios", "calidad_producto", "decisiones"],
    maturityRange: ["explorador", "escalador"],
    technicalComplexity: 2,
    complexityLabel: "quick_win",
    expectedTimeToPilot: "2–4 semanas",
    problemSolved: "Hay ideas de nuevos servicios o funcionalidades, pero no tiempo ni forma de probarlas sin un desarrollo largo.",
    howItWorks: "Se construye un prototipo funcional en pocas semanas, con IA donde aporte, se prueba con un grupo de usuarios y se decide con datos si seguir, cambiar o parar.",
    benefitDescription: "Decisiones de inversión con evidencia y menos riesgo de construir lo que nadie usa.",
    requiredInputs: ["La idea y la hipótesis que se quiere validar", "Usuarios dispuestos a probar", "Criterio de éxito"],
    recommendedFirstStep: "Escribir en una página qué problema resuelve la idea y para quién.",
    amacruxFit: "Amacrux diseña y construye el prototipo y acompaña la validación.",
    relatedTools: ["Herramientas de prototipado", "Analítica", "Formularios de feedback"],
    commercialCta: "Prototipar una idea con Amacrux",
  },
  {
    id: "optimizacion-onboarding",
    title: "Mejorar el alta y los primeros pasos de los usuarios",
    category: "producto_digital",
    applicableProfiles: ["producto_innovacion", "marketing_ventas", "tecnologico"],
    applicableSectors: ["tecnologia_software", "educacion", "finanzas_seguros"],
    problemSignals: ["atencion_cliente", "soporte_interno", "desarrollo_software"],
    desiredOutcomes: ["calidad_producto", "aumentar_ventas", "mejorar_atencion"],
    maturityRange: ["en_adopcion", "escalador"],
    technicalComplexity: 3,
    complexityLabel: "piloto_baja",
    expectedTimeToPilot: "4–6 semanas",
    problemSolved: "Muchos usuarios abandonan en el alta o en los primeros usos y el soporte recibe siempre las mismas dudas.",
    howItWorks: "Se analiza dónde se abandona, se rediseñan los pasos críticos y se añade ayuda contextual con IA (guías, respuestas dentro del producto) medida con analítica.",
    benefitDescription: "Más usuarios que llegan a usar el producto y menos carga de soporte en las primeras semanas.",
    requiredInputs: ["Analítica de producto o datos de abandono", "Preguntas frecuentes de soporte", "Acceso al equipo de producto"],
    recommendedFirstStep: "Medir en qué paso del alta se pierde más gente.",
    amacruxFit: "Amacrux analiza, diseña y desarrolla las mejoras junto al equipo de producto.",
    relatedTools: ["Analítica de producto", "Producto propio", "Herramientas de ayuda en la aplicación"],
    commercialCta: "Mejorar el onboarding con Amacrux",
  },
];

/** Recomendaciones educativas por perfil cuando faltan señales (siempre baja complejidad). */
export const DEFAULTS_BY_PROFILE: Record<ProfileSegment, string[]> = {
  decisor_negocio: ["recordatorios-y-seguimiento", "clasificacion-solicitudes", "reporting-automatico", "respuestas-guiadas-whatsapp"],
  operaciones: ["reporting-automatico", "recordatorios-y-seguimiento", "clasificacion-documental", "clasificacion-solicitudes"],
  tecnologico: ["reporting-automatico", "sincronizacion-entre-herramientas", "asistente-interno-conocimiento", "prototipo-validacion"],
  ingenieria: ["documentacion-tecnica-viva", "asistentes-desarrollo", "generacion-tests-y-qa", "prototipo-validacion"],
  producto_innovacion: ["prototipo-validacion", "documentacion-tecnica-viva", "optimizacion-onboarding", "reporting-automatico"],
  marketing_ventas: ["cualificacion-leads", "respuestas-guiadas-whatsapp", "recordatorios-y-seguimiento", "generacion-presupuestos"],
  consultor_independiente: ["recordatorios-y-seguimiento", "clasificacion-documental", "generacion-presupuestos", "prototipo-validacion"],
};

void ALL_PROFILES;
